### ISSUE TITLE
Dispositivos Móviles

### ISSUE THREAD

**Issue by mgutierrezc** [jmgutierreza/pandemia#9]
Hola muchachos,

Una pregunta sobre sus sesiones ¿Van a desear que puedan entrar participantes desde sus celulares/tablets o solo desde sus computadoras? 

Estaré atento a sus respuestas,

**Comment by jmgutierreza** [comment]
Hola Marco,

Por nosotros no hay problema que puedan utilizar sus celulares o tablets.

Saludos,
